### ISSUE TITLE
unexpected EOF while looking for matching

### ISSUE THREAD

**Issue by zghwi** [acidicneko/moon#3]
![image](https://user-images.githubusercontent.com/73612690/121715675-d4b7bf00-cae7-11eb-826a-fbca24ce67eb.png)

_I use msys2 for windows because why not :)_
Your project looks amazing, and I wanna try it because my bash prompt is not good :/

**Comment by acidicneko** [comment]
Seems weird. What version of Bash are ya using?

**Comment by zghwi** [comment]
oh, the bash version is ...
![image](https://user-images.githubusercontent.com/73612690/121720986-688b8a00-caec-11eb-8f12-b8bf8a783173.png)

**Comment by acidicneko** [comment]
Hmph. It is the one I am using too. Try removing `~/.config/moon/` and remove the line `. /home/user/.config/moon/moon.sh` from ~/.bashrc.
And then reinstall again. What I can guess is you have somehow messed with Moon's files.

**Comment by zghwi** [comment]
Ok, I'll try when I'll be at home ;)

**Comment by acidicneko** [comment]
Okay. So should we close this issue now?

**Comment by zghwi** [comment]
tried it on google cloud shell and it worked (except the icons)

**Comment by zghwi** [comment]
![image](https://user-images.githubusercontent.com/73612690/121816068-24ca8900-cc82-11eb-8dc7-2ad3294ae212.png)
works on MobaXterm but the prompt is right-aligned

**Comment by acidicneko** [comment]
Yes. Right aligned prompt is faced by some other guy too. Can ya close this issue and open a new one for this problem

**Comment by zghwi** [comment]
oke
